// Package commissioning provides the business logic for Matter device commissioning.
//
// It coordinates:
//   - Payload parsing (QR codes and manual pairing codes)
//   - Verifier computation (passcodes to PASE inputs)
//   - Commissioner flow (controller-side commissioning)
//   - Device flow (commissionee window management)
package commissioning

import (
	"github.com/backkem/matter/pkg/commissioning/payload"
	"github.com/backkem/matter/pkg/securechannel/pase"
)

// SetupParams holds parameters for PASE session setup.
// These parameters are extracted from the onboarding payload and
// used to establish a secure channel with the device.
type SetupParams struct {
	// Passcode is the 27-bit setup PIN code from the payload.
	Passcode uint32

	// Salt is the PBKDF2 salt (16-32 bytes).
	// May come from optional TLV data or be generated by the device.
	Salt []byte

	// Iterations is the PBKDF2 iteration count (1000-100000).
	// May come from optional TLV data or be provided by the device.
	Iterations uint32
}

// SetupParamsFromPayload extracts SetupParams from a SetupPayload.
//
// If the payload contains optional TLV data with PBKDF parameters,
// those values are used. Otherwise, defaults are applied and a
// random salt is generated.
func SetupParamsFromPayload(p *payload.SetupPayload) (*SetupParams, error) {
	pbkdf, err := payload.ExtractPBKDFParams(p)
	if err != nil {
		return nil, err
	}

	return &SetupParams{
		Passcode:   p.Passcode,
		Salt:       pbkdf.Salt,
		Iterations: pbkdf.Iterations,
	}, nil
}

// GenerateVerifier computes the PASE verifier from setup parameters.
//
// This is used by the commissionee (device) side to prepare for PASE.
// The verifier consists of:
//   - w0: First half of PBKDF output (mod p)
//   - L:  w1 * P (point multiplication)
//
// See Matter Specification Section 3.10 for details.
func GenerateVerifier(params *SetupParams) (*pase.Verifier, error) {
	return pase.GenerateVerifier(params.Passcode, params.Salt, params.Iterations)
}

// ComputeW0W1 computes w0 and w1 from setup parameters.
//
// This is used by the commissioner (initiator) side during PASE.
// The commissioner knows the passcode and computes w0, w1 directly,
// while the device only stores the verifier (w0, L).
//
// See Matter Specification Section 3.10 for details.
func ComputeW0W1(params *SetupParams) (w0, w1 []byte, err error) {
	return pase.ComputeW0W1(params.Passcode, params.Salt, params.Iterations)
}

// ValidatePasscode checks if a passcode is valid per spec requirements.
//
// Invalid passcodes include:
//   - 0 and values > 99999998
//   - All same digit patterns (11111111, 22222222, etc.)
//   - Sequential patterns (12345678, 87654321)
//
// See Matter Specification Section 5.1.7.1.
func ValidatePasscode(passcode uint32) error {
	return pase.ValidatePasscode(passcode)
}

// GenerateSalt generates a cryptographically random PBKDF2 salt.
// Returns a 16-byte salt suitable for PASE verifier generation.
func GenerateSalt() ([]byte, error) {
	params, err := payload.DefaultPBKDFParams()
	if err != nil {
		return nil, err
	}
	return params.Salt, nil
}
